import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { useQuery } from '@apollo/client';
import { ExploreCard, SearchHeader } from '~/components/domains';
import { GET_ALL_RECIPES } from '~/graphql/Queries';
import { RecipeAllData } from '~/types/recipe';
import styles from '~/styles/Home.module.css';

export default function Home() {
  const { loading, error, data } = useQuery<RecipeAllData>(GET_ALL_RECIPES);
  const router = useRouter();
  const [inputState, setInputState] = useState({
    select: 'tag',
    search: '',
  });

  const handleSearchClick = () => {
    router.push({
      pathname: '/search',
      query: { [inputState.select]: inputState.search },
    });
  };

  return (
    <>
      <Head>
        <title>Recipe</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SearchHeader
        inputState={inputState}
        setInputState={setInputState}
        handleSearchClick={handleSearchClick}
      />
      <main className={styles.main}>
        {data?.recipes.data.map((recipe) => (
          <ExploreCard
            key={recipe.id}
            id={recipe.id}
            data={recipe.attributes}
          />
        ))}
      </main>

      <footer className={styles.footer}>footer</footer>
    </>
  );
}
